/*
 *
 *  Copyright 2025 Rahul Thakur
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.pragmatik.buildtools.cicd;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import org.springframework.stereotype.Component;

/**
 * GitHub Actions target — generates and validates GitHub Actions workflow YAML.
 *
 * <p>Converts a {@link CiCdPipeline} intermediate representation into a valid
 * {@code .github/workflows/*.yml} file. Uses manual YAML formatting with no
 * external rendering library (as per spec: "SnakeYAML for parsing only").
 *
 * <p>Validation delegates to {@link CiCdValidator} for rich YAML parsing and
 * schema checks beyond the basic string-level checks maintained here for
 * backward compatibility.
 */
@Component
public class GitHubActionsGenerator implements CiCdTarget {

    private static final String INDENT = "  ";
    private static final String DOUBLE_INDENT = INDENT + INDENT;
    private static final String TRIPLE_INDENT = INDENT + INDENT + INDENT;

    private final CiCdValidator validator;

    /** Default constructor for direct instantiation in tests. */
    public GitHubActionsGenerator() {
        this.validator = new CiCdValidator();
    }

    /** Injection constructor. */
    public GitHubActionsGenerator(CiCdValidator validator) {
        this.validator = validator;
    }

    @Override
    public String name() {
        return "github-actions";
    }

    @Override
    public String generate(CiCdPipeline pipeline) {
        StringBuilder yaml = new StringBuilder(2048);
        yaml.append("# Generated by mcp-server-jvm-build-tools v1.0.0\n");

        // name
        yaml.append("name: ").append(yamlValue(pipeline.name())).append("\n");

        // on — triggers
        yaml.append("on:\n");
        appendTriggers(yaml, pipeline.on());

        // env (optional)
        if (pipeline.env() != null && !pipeline.env().isEmpty()) {
            yaml.append("env:\n");
            for (Map.Entry<String, String> e : pipeline.env().entrySet()) {
                yaml.append(INDENT)
                        .append(yamlKey(e.getKey()))
                        .append(": ")
                        .append(yamlValue(e.getValue()))
                        .append("\n");
            }
        }

        // defaults (optional)
        if (pipeline.defaults() != null) {
            yaml.append("defaults:\n");
            if (pipeline.defaults().shell() != null) {
                yaml.append(INDENT).append("run:\n");
                yaml.append(DOUBLE_INDENT)
                        .append("shell: ")
                        .append(yamlValue(pipeline.defaults().shell()))
                        .append("\n");
            }
            if (pipeline.defaults().workingDirectory() != null) {
                yaml.append(INDENT).append("run:\n");
                yaml.append(DOUBLE_INDENT)
                        .append("working-directory: ")
                        .append(yamlValue(pipeline.defaults().workingDirectory()))
                        .append("\n");
            }
        }

        // permissions (optional)
        if (pipeline.permissions() != null) {
            yaml.append("permissions:\n");
            CiCdPermissions p = pipeline.permissions();
            appendIfNotNull(yaml, "contents", p.contents());
            appendIfNotNull(yaml, "issues", p.issues());
            appendIfNotNull(yaml, "pull-requests", p.pullRequests());
            appendIfNotNull(yaml, "packages", p.packages());
            appendIfNotNull(yaml, "id-token", p.idToken());
        }

        // jobs
        yaml.append("jobs:\n");
        for (CiCdJob job : pipeline.jobs()) {
            String jobId = (job.id() != null) ? job.id() : sanitizeJobId(job.name());
            yaml.append(INDENT).append(yamlKey(jobId)).append(":\n");

            // Display name
            yaml.append(DOUBLE_INDENT)
                    .append("name: ")
                    .append(yamlValue(job.name()))
                    .append("\n");

            // runs-on
            yaml.append(DOUBLE_INDENT)
                    .append("runs-on: ")
                    .append(yamlValue(job.runsOn()))
                    .append("\n");

            // needs
            if (job.needs() != null && !job.needs().isEmpty()) {
                String needsStr = job.needs().stream().map(this::yamlValue).collect(Collectors.joining(", "));
                yaml.append(DOUBLE_INDENT).append("needs: [").append(needsStr).append("]\n");
            }

            // condition
            if (job.condition() != null && !job.condition().isEmpty()) {
                yaml.append(DOUBLE_INDENT)
                        .append("if: ")
                        .append(yamlValue(job.condition()))
                        .append("\n");
            }

            // timeout-minutes
            if (job.timeoutMinutes() != 60) {
                yaml.append(DOUBLE_INDENT)
                        .append("timeout-minutes: ")
                        .append(job.timeoutMinutes())
                        .append("\n");
            }

            // strategy / matrix
            if (job.strategy() != null) {
                CiCdMatrixStrategy strategy = job.strategy();
                yaml.append(DOUBLE_INDENT).append("strategy:\n");
                if (!strategy.failFast()) {
                    yaml.append(TRIPLE_INDENT).append("fail-fast: false\n");
                }
                boolean hasJava = strategy.java() != null && !strategy.java().isEmpty();
                boolean hasOs = strategy.os() != null && !strategy.os().isEmpty();
                if (hasJava || hasOs) {
                    yaml.append(TRIPLE_INDENT).append("matrix:\n");
                    if (hasJava) {
                        yaml.append(TRIPLE_INDENT)
                                .append(INDENT)
                                .append("java: ")
                                .append(toYamlArray(strategy.java()))
                                .append("\n");
                    }
                    if (hasOs) {
                        yaml.append(TRIPLE_INDENT)
                                .append(INDENT)
                                .append("os: ")
                                .append(toYamlArray(strategy.os()))
                                .append("\n");
                    }
                }
            }

            // env (job-level)
            if (job.env() != null && !job.env().isEmpty()) {
                yaml.append(DOUBLE_INDENT).append("env:\n");
                for (Map.Entry<String, String> e : job.env().entrySet()) {
                    yaml.append(TRIPLE_INDENT)
                            .append(yamlKey(e.getKey()))
                            .append(": ")
                            .append(yamlValue(e.getValue()))
                            .append("\n");
                }
            }

            // steps
            yaml.append(DOUBLE_INDENT).append("steps:\n");
            for (CiCdStep step : job.steps()) {
                yaml.append(TRIPLE_INDENT)
                        .append("- name: ")
                        .append(yamlValue(step.name()))
                        .append("\n");

                // uses
                if (step.uses() != null && !step.uses().isEmpty()) {
                    yaml.append(TRIPLE_INDENT)
                            .append(INDENT)
                            .append("uses: ")
                            .append(yamlValue(step.uses()))
                            .append("\n");
                }

                // run
                if (step.run() != null && !step.run().isEmpty()) {
                    yaml.append(TRIPLE_INDENT)
                            .append(INDENT)
                            .append("run: ")
                            .append(yamlValue(step.run()))
                            .append("\n");
                }

                // with
                if (step.with() != null && !step.with().isEmpty()) {
                    yaml.append(TRIPLE_INDENT).append(INDENT).append("with:\n");
                    for (Map.Entry<String, Object> w : step.with().entrySet()) {
                        yaml.append(TRIPLE_INDENT)
                                .append(DOUBLE_INDENT)
                                .append(yamlKey(w.getKey()))
                                .append(": ");
                        Object val = w.getValue();
                        if (val instanceof String s) {
                            yaml.append(yamlValue(s));
                        } else if (val instanceof Number || val instanceof Boolean) {
                            yaml.append(val);
                        } else {
                            yaml.append(yamlValue(String.valueOf(val)));
                        }
                        yaml.append("\n");
                    }
                }

                // env (step-level)
                if (step.env() != null && !step.env().isEmpty()) {
                    yaml.append(TRIPLE_INDENT).append(INDENT).append("env:\n");
                    for (Map.Entry<String, String> e : step.env().entrySet()) {
                        yaml.append(TRIPLE_INDENT)
                                .append(DOUBLE_INDENT)
                                .append(yamlKey(e.getKey()))
                                .append(": ")
                                .append(yamlValue(e.getValue()))
                                .append("\n");
                    }
                }

                // condition
                if (step.condition() != null && !step.condition().isEmpty()) {
                    yaml.append(TRIPLE_INDENT)
                            .append(INDENT)
                            .append("if: ")
                            .append(yamlValue(step.condition()))
                            .append("\n");
                }

                // continue-on-error
                if (step.continueOnError()) {
                    yaml.append(TRIPLE_INDENT).append(INDENT).append("continue-on-error: true\n");
                }

                // timeout-minutes
                if (step.timeoutMinutes() != null) {
                    yaml.append(TRIPLE_INDENT)
                            .append(INDENT)
                            .append("timeout-minutes: ")
                            .append(step.timeoutMinutes())
                            .append("\n");
                }

                // working-directory
                if (step.workingDirectory() != null && !step.workingDirectory().isEmpty()) {
                    yaml.append(TRIPLE_INDENT)
                            .append(INDENT)
                            .append("working-directory: ")
                            .append(yamlValue(step.workingDirectory()))
                            .append("\n");
                }
            }
        }

        return yaml.toString();
    }

    @Override
    public ValidationResult validate(String configContent) {
        // Delegate to CiCdValidator for full YAML parsing and schema validation
        CiCdValidator.ValidationResult richResult = validator.validate(configContent);
        if (!richResult.valid()) {
            return ValidationResult.error(richResult.errorMessage());
        }
        return ValidationResult.success();
    }

    // ─── Private helpers ──────────────────────────────────────────────

    private void appendTriggers(StringBuilder yaml, CiCdTrigger trigger) {
        boolean hasPush = trigger.push() != null;
        boolean hasPr = trigger.pullRequest() != null;
        boolean hasRelease = trigger.release() != null;
        boolean hasSchedule = trigger.schedule() != null && !trigger.schedule().isEmpty();
        boolean hasWorkflowDispatch = trigger.workflowDispatch();

        // Push trigger
        if (hasPush) {
            yaml.append(INDENT).append("push:\n");
            CiCdPushTrigger push = trigger.push();
            if (push.branches() != null && !push.branches().isEmpty()) {
                yaml.append(DOUBLE_INDENT)
                        .append("branches: ")
                        .append(toYamlArray(push.branches()))
                        .append("\n");
            }
            if (push.paths() != null && !push.paths().isEmpty()) {
                yaml.append(DOUBLE_INDENT)
                        .append("paths: ")
                        .append(toYamlArray(push.paths()))
                        .append("\n");
            }
        }

        // Pull request trigger
        if (hasPr) {
            yaml.append(INDENT).append("pull_request:\n");
            CiCdPrTrigger pr = trigger.pullRequest();
            if (pr.branches() != null && !pr.branches().isEmpty()) {
                yaml.append(DOUBLE_INDENT)
                        .append("branches: ")
                        .append(toYamlArray(pr.branches()))
                        .append("\n");
            }
        }

        // Release trigger
        if (hasRelease) {
            yaml.append(INDENT).append("release:\n");
            CiCdReleaseTrigger release = trigger.release();
            if (release.types() != null && !release.types().isEmpty()) {
                yaml.append(DOUBLE_INDENT)
                        .append("types: ")
                        .append(toYamlArray(release.types()))
                        .append("\n");
            }
        }

        // Schedule trigger
        if (hasSchedule) {
            yaml.append(INDENT).append("schedule:\n");
            for (CiCdScheduleEntry entry : trigger.schedule()) {
                yaml.append(DOUBLE_INDENT)
                        .append("- cron: ")
                        .append(yamlValue(entry.cron()))
                        .append("\n");
            }
        }

        // Workflow dispatch
        if (hasWorkflowDispatch) {
            yaml.append(INDENT).append("workflow_dispatch:\n");
        }
    }

    private String toYamlArray(List<String> items) {
        return items.stream().map(this::yamlValue).collect(Collectors.joining(", ", "[", "]"));
    }

    private String yamlValue(String s) {
        if (s == null) return "''";
        // If it starts with ${{, it's a GitHub expression — don't quote
        if (s.startsWith("${{")) {
            return s;
        }
        // Check if quoting is needed
        boolean needsQuotes = s.isEmpty()
                || s.contains(" ")
                || s.contains("#")
                || s.contains(":")
                || s.contains("[")
                || s.startsWith("&")
                || s.startsWith("*")
                || s.startsWith("!")
                || s.startsWith("|")
                || s.startsWith(">");
        if (needsQuotes) {
            return "'" + s.replace("'", "''") + "'";
        }
        return s;
    }

    private String yamlKey(String key) {
        // Simple keys generally don't need quoting unless they contain special chars
        boolean needsQuotes = key.contains(":")
                || key.contains("#")
                || key.contains("{")
                || key.contains("[")
                || key.contains(",")
                || key.contains(" ")
                || key.contains("@");
        if (needsQuotes) {
            return "'" + key.replace("'", "''") + "'";
        }
        return key;
    }

    private void appendIfNotNull(StringBuilder yaml, String key, String value) {
        if (value != null) {
            yaml.append(INDENT)
                    .append(yamlKey(key))
                    .append(": ")
                    .append(yamlValue(value))
                    .append("\n");
        }
    }

    private String sanitizeJobId(String name) {
        return name.toLowerCase()
                .replaceAll("[^a-z0-9_]", "_")
                .replaceAll("_+", "_")
                .replaceAll("^_|_$", "");
    }
}
