/*
 *
 *  Copyright 2025 Rahul Thakur
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.pragmatik.buildtools.tool;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertTimeoutPreemptively;

import com.networknt.schema.Schema;
import com.networknt.schema.SchemaLocation;
import com.networknt.schema.SchemaRegistry;
import com.networknt.schema.SpecificationVersion;
import com.pragmatik.buildtools.application.BuildToolsApplication;
import java.time.Duration;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.ai.tool.ToolCallback;
import org.springframework.ai.tool.ToolCallbackProvider;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

/**
 * Validates that every MCP tool {@code inputSchema} generated by Spring AI complies with the MCP
 * upcoming-spec requirement (SEP-2106) to be a valid JSON Schema 2020-12 document.
 *
 * <h2>Recorded dialect finding (acceptance criterion: confirm/record the emitted dialect)</h2>
 *
 * <p>Spring AI {@code 2.0.0-RC2} generates tool input schemas via {@code
 * org.springframework.ai.util.json.schema.JsonSchemaGenerator}, which uses the victools schema
 * generator configured with {@code com.github.victools.jsonschema.generator.SchemaVersion.DRAFT_2020_12}
 * and explicitly stamps the root with {@code "$schema":
 * "https://json-schema.org/draft/2020-12/schema"}. It hoists any {@code $defs} to the document root and
 * sets {@code additionalProperties: false} on object schemas. <strong>The emitted dialect is therefore
 * already JSON Schema 2020-12 — there is no draft-07 divergence and no migration path is required.</strong>
 * This test enforces that finding so a future Spring AI regression to an older dialect fails the build.
 *
 * <h2>What is enforced (SEP-2106)</h2>
 *
 * <ul>
 *   <li>Each {@code inputSchema} is a non-null JSON <em>object</em> with a root {@code type: "object"}.
 *   <li>When a {@code $schema} keyword is present it declares 2020-12 (the spec default when absent).
 *   <li>Each schema validates against the official JSON Schema 2020-12 meta-schema, within a bounded
 *       validation time budget.
 *   <li>Each schema compiles cleanly under the 2020-12 dialect (it loads/parses without error under
 *       the official dialect; note {@code com.networknt} v3 resolves {@code $ref} lazily, so compilation
 *       alone does not eagerly resolve references — real local {@code $ref} resolution is proven by the
 *       composition guard test via instance validation).
 *   <li>No schema relies on auto-dereferencing of <strong>external</strong> {@code $ref} URIs — only
 *       local fragment references ({@code #...}) are permitted.
 *   <li>Schema container-nesting depth and {@code $defs} count are bounded (defense for composition keywords such
 *       as {@code oneOf}/{@code anyOf}/{@code allOf}), bounding resource and validation cost.
 * </ul>
 *
 * <p>The 2020-12 meta-schema and the {@link SchemaRegistry} come from {@code
 * com.networknt:json-schema-validator} (a compile-scope dependency already on the MCP stack via {@code
 * mcp-json-jackson3}); the meta-schema is loaded from the bundled classpath resource, so this test never
 * dereferences anything over the network.
 */
@SpringBootTest(classes = BuildToolsApplication.class)
@DisplayName("Tool inputSchema JSON Schema 2020-12 compliance (SEP-2106)")
class ToolJsonSchemaComplianceTest {

    /** Canonical JSON Schema 2020-12 dialect identifier. */
    private static final String DIALECT_2020_12 = "https://json-schema.org/draft/2020-12/schema";

    /** Upper bound on schema container-nesting depth (bounds composition-keyword resource cost). */
    private static final int MAX_SCHEMA_DEPTH = 20;

    /** Upper bound on the total number of {@code $defs}/{@code definitions} entries. */
    private static final int MAX_DEFS = 64;

    /** Time budget for validating a single schema against the meta-schema. */
    private static final Duration VALIDATION_TIMEOUT = Duration.ofSeconds(5);

    private static JsonMapper mapper;
    private static SchemaRegistry registry;
    private static Schema metaSchema;

    @Autowired
    private ToolCallbackProvider toolCallbackProvider;

    @BeforeAll
    static void setUp() {
        mapper = JsonMapper.builder().build();
        registry = SchemaRegistry.withDefaultDialect(SpecificationVersion.DRAFT_2020_12);
        // Loaded from the bundled classpath resource — no network dereference.
        metaSchema = registry.getSchema(SchemaLocation.of(SpecificationVersion.DRAFT_2020_12.getDialectId()));
    }

    // ──────────────────────────────────────────────
    //  Compliance across all registered tools
    // ──────────────────────────────────────────────

    @Test
    @DisplayName("every registered tool inputSchema is a valid JSON Schema 2020-12 object")
    void everyToolInputSchemaIsValid2020_12() {
        ToolCallback[] callbacks = toolCallbackProvider.getToolCallbacks();
        assertThat(callbacks).as("at least one MCP tool must be registered").isNotEmpty();

        Map<String, String> violations = new LinkedHashMap<>();
        for (ToolCallback callback : callbacks) {
            String name = callback.getToolDefinition().name();
            String inputSchema = callback.getToolDefinition().inputSchema();
            try {
                validateInputSchema(inputSchema);
            } catch (AssertionError | RuntimeException e) {
                violations.put(name, e.getMessage());
            }
        }

        assertThat(violations)
                .as("tool inputSchema JSON Schema 2020-12 violations: %s", violations)
                .isEmpty();
    }

    @Test
    @DisplayName("every tool declares the 2020-12 dialect (no draft-07 divergence)")
    void everyToolDeclaresDraft2020_12() {
        ToolCallback[] callbacks = toolCallbackProvider.getToolCallbacks();
        assertThat(callbacks).isNotEmpty();

        for (ToolCallback callback : callbacks) {
            JsonNode root = mapper.readTree(callback.getToolDefinition().inputSchema());
            JsonNode schemaKeyword = root.path("$schema");
            assertThat(schemaKeyword.isMissingNode())
                    .as(
                            "tool '%s' must declare $schema (Spring AI RC2 stamps the 2020-12 dialect)",
                            callback.getToolDefinition().name())
                    .isFalse();
            assertThat(schemaKeyword.asString())
                    .as(
                            "tool '%s' must declare the 2020-12 dialect",
                            callback.getToolDefinition().name())
                    .isEqualTo(DIALECT_2020_12);
        }
    }

    /** Runs every SEP-2106 check on a single tool input schema. */
    private void validateInputSchema(String inputSchema) {
        assertThat(inputSchema).as("inputSchema must not be null/blank").isNotBlank();

        JsonNode root = mapper.readTree(inputSchema);
        assertThat(root.isObject())
                .as("inputSchema root MUST be a JSON object (not null/array/scalar)")
                .isTrue();

        JsonNode type = root.path("type");
        assertThat(type.isString()).as("root 'type' keyword must be present").isTrue();
        assertThat(type.asString())
                .as("root 'type' must be 'object' for tool inputs")
                .isEqualToIgnoringCase("object");

        JsonNode schemaKeyword = root.path("$schema");
        if (!schemaKeyword.isMissingNode()) {
            assertThat(schemaKeyword.asString())
                    .as("when present, $schema must declare the 2020-12 dialect")
                    .isEqualTo(DIALECT_2020_12);
        }

        // Formal 2020-12 validity, with a bounded validation-time budget.
        List<com.networknt.schema.Error> errors =
                assertTimeoutPreemptively(VALIDATION_TIMEOUT, () -> metaSchema.validate(root));
        assertThat(errors)
                .as("schema must validate against the JSON Schema 2020-12 meta-schema")
                .isEmpty();

        // Compiling under the 2020-12 dialect proves the schema loads/parses without error. Note that
        // com.networknt v3 resolves $ref lazily (at validate() time), so this does not by itself prove
        // local $ref resolution; that guarantee is exercised by the composition guard test via instance
        // validation. External $ref dereferencing is forbidden by the explicit local-ref check below.
        assertDoesNotThrow(() -> registry.getSchema(root), "schema must compile under the 2020-12 dialect");

        // No external $ref dereferencing: only local fragment references are allowed.
        List<String> refs = new ArrayList<>();
        collectRefs(root, refs);
        for (String ref : refs) {
            assertThat(isLocalRef(ref))
                    .as("$ref '%s' must be a local fragment; external $ref dereferencing is forbidden", ref)
                    .isTrue();
        }

        // Bound resource cost for composition / deeply nested schemas.
        assertThat(maxDepth(root))
                .as("schema container-nesting depth must be bounded")
                .isLessThanOrEqualTo(MAX_SCHEMA_DEPTH);
        assertThat(countDefsEntries(root))
                .as("schema $defs count must be bounded")
                .isLessThanOrEqualTo(MAX_DEFS);
    }

    // ──────────────────────────────────────────────
    //  Guard tests: prove the bounding logic actually bites
    //  (composition keywords are not used by any current tool, but the
    //   guards must enforce SEP-2106 bounds if a future tool adds them).
    // ──────────────────────────────────────────────

    @Nested
    @DisplayName("schema-bound guards")
    class SchemaBoundGuards {

        @Test
        @DisplayName("classifies local vs external $ref references")
        void classifiesRefs() {
            assertThat(isLocalRef("#/$defs/Positive")).isTrue();
            assertThat(isLocalRef("#")).isTrue();
            assertThat(isLocalRef("#positiveAnchor")).isTrue();
            assertThat(isLocalRef("https://example.com/schema.json")).isFalse();
            assertThat(isLocalRef("http://example.com/schema.json#/Foo")).isFalse();
            assertThat(isLocalRef("file:///etc/passwd")).isFalse();
            assertThat(isLocalRef("urn:example:schema")).isFalse();
            assertThat(isLocalRef("common.json#/Foo")).isFalse();
            assertThat(isLocalRef(null)).isFalse();
        }

        @Test
        @DisplayName("collectRefs flags an external $ref in a composition schema")
        void collectRefsFindsExternalRef() {
            String schema =
                    """
                    {
                      "$schema": "https://json-schema.org/draft/2020-12/schema",
                      "type": "object",
                      "properties": {
                        "v": { "anyOf": [ { "$ref": "https://evil.example/x.json" }, { "type": "null" } ] }
                      }
                    }
                    """;
            List<String> refs = new ArrayList<>();
            collectRefs(mapper.readTree(schema), refs);
            assertThat(refs).containsExactly("https://evil.example/x.json");
            assertThat(refs.stream().allMatch(ToolJsonSchemaComplianceTest::isLocalRef))
                    .isFalse();
        }

        @Test
        @DisplayName("maxDepth detects schemas deeper than the bound")
        void maxDepthDetectsDeepSchema() {
            StringBuilder open = new StringBuilder();
            StringBuilder close = new StringBuilder();
            int depth = MAX_SCHEMA_DEPTH + 5;
            for (int i = 0; i < depth; i++) {
                open.append("{\"properties\":{\"n\":");
                close.append("}}");
            }
            String deep = open + "{\"type\":\"string\"}" + close;
            assertThat(maxDepth(mapper.readTree(deep))).isGreaterThan(MAX_SCHEMA_DEPTH);

            String shallow =
                    """
                    { "type": "object", "properties": { "name": { "type": "string" } } }
                    """;
            assertThat(maxDepth(mapper.readTree(shallow))).isLessThanOrEqualTo(MAX_SCHEMA_DEPTH);
        }

        @Test
        @DisplayName("countDefsEntries detects schemas exceeding the $defs bound")
        void countDefsDetectsManyDefs() {
            StringBuilder defs = new StringBuilder();
            int count = MAX_DEFS + 3;
            for (int i = 0; i < count; i++) {
                if (i > 0) {
                    defs.append(',');
                }
                defs.append("\"d").append(i).append("\":{\"type\":\"string\"}");
            }
            String schema = "{\"type\":\"object\",\"$defs\":{" + defs + "}}";
            assertThat(countDefsEntries(mapper.readTree(schema))).isGreaterThan(MAX_DEFS);
        }

        @Test
        @DisplayName("a valid composition schema validates within budget and resolves local $ref")
        void compositionSchemaResolvesLocalRefWithinBudget() {
            String schema =
                    """
                    {
                      "$schema": "https://json-schema.org/draft/2020-12/schema",
                      "type": "object",
                      "$defs": { "positive": { "type": "integer", "minimum": 1 } },
                      "properties": {
                        "value": { "oneOf": [ { "$ref": "#/$defs/positive" }, { "type": "null" } ] }
                      },
                      "required": [ "value" ],
                      "additionalProperties": false
                    }
                    """;
            JsonNode root = mapper.readTree(schema);

            // The schema document itself is valid 2020-12, within the time budget.
            List<com.networknt.schema.Error> metaErrors =
                    assertTimeoutPreemptively(VALIDATION_TIMEOUT, () -> metaSchema.validate(root));
            assertThat(metaErrors).isEmpty();

            // Local $ref resolution works: a conforming instance passes, a non-conforming one fails.
            Schema compiled = registry.getSchema(root);
            assertThat(compiled.validate(mapper.readTree("{\"value\": 3}"))).isEmpty();
            assertThat(compiled.validate(mapper.readTree("{\"value\": -1}"))).isNotEmpty();

            // All references are local and bounds are respected.
            List<String> refs = new ArrayList<>();
            collectRefs(root, refs);
            assertThat(refs).isNotEmpty().allMatch(ToolJsonSchemaComplianceTest::isLocalRef);
            assertThat(maxDepth(root)).isLessThanOrEqualTo(MAX_SCHEMA_DEPTH);
            assertThat(countDefsEntries(root)).isLessThanOrEqualTo(MAX_DEFS);
        }
    }

    // ──────────────────────────────────────────────
    //  Schema-walk helpers
    // ──────────────────────────────────────────────

    /** A reference is local when it is a pure fragment (starts with {@code #}); otherwise it is external. */
    private static boolean isLocalRef(String ref) {
        return ref != null && ref.startsWith("#");
    }

    /** Collects every {@code $ref} string value found anywhere in the schema tree. */
    private static void collectRefs(JsonNode node, List<String> refs) {
        if (node.isObject()) {
            JsonNode ref = node.get("$ref");
            if (ref != null && ref.isString()) {
                refs.add(ref.asString());
            }
        }
        if (node.isObject() || node.isArray()) {
            for (JsonNode child : node) {
                collectRefs(child, refs);
            }
        }
    }

    /** Maximum container-nesting depth of the schema tree (leaves have depth 0). */
    private static int maxDepth(JsonNode node) {
        if (!node.isObject() && !node.isArray()) {
            return 0;
        }
        int deepest = 0;
        for (JsonNode child : node) {
            deepest = Math.max(deepest, maxDepth(child));
        }
        return 1 + deepest;
    }

    /** Total number of entries across every {@code $defs}/{@code definitions} object in the tree. */
    private static int countDefsEntries(JsonNode node) {
        int count = 0;
        if (node.isObject()) {
            for (String key : List.of("$defs", "definitions")) {
                JsonNode defs = node.get(key);
                if (defs != null && defs.isObject()) {
                    count += defs.size();
                }
            }
        }
        if (node.isObject() || node.isArray()) {
            for (JsonNode child : node) {
                count += countDefsEntries(child);
            }
        }
        return count;
    }
}
